### ISSUE TITLE
Notifications email body

### ISSUE THREAD

**Issue by smcllns** [andreyLevushkin/Techmeetup-Site#10]
Can you change body of message to (apparently it's really confusing):

[start]
Don't want to receive every reply on this topic? <a href="mutefunction">Mute!</a>

See this discussion and reply with the link below:
http://87.246.111.22/discussiondetailpage/718

[username] posted:
Original message

[username] posted:
reply 1

[username] posted:
reply 2

[a couple of line breaks down to the footer]
<br>
## <br>

Reply to this message
Mute any further notifications on this topic
You received this message because you care about tech (and your notifications are enabled at www.techmeetup.co.uk).
If you don’t want these timely notifications of what’s happening around you, click here to remove your account from the service, or here to remain on the service but disable notifications
[end]

**Comment by andreyLevushkin** [comment]
done i think
