### ISSUE TITLE
Notifications as spam

### ISSUE THREAD

**Issue by smcllns** [andreyLevushkin/Techmeetup-Site#9]
Oli said:
"Thunderbird thinks this message might be a scam and that you might be trying to thieve my bank account details! :-O"

Is there anything you can do for this?

**Comment by MariusCiocanel** [comment]
I think that's because of the way Thunderbird works. If it sees a lot of similar emails it marks them as spam.

**Comment by andreyLevushkin** [comment]
Nothing i can do about that.
